# Generated by Django 4.1.7 on 2023-06-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiuserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogdb',
            name='User_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
