# Generated by Django 4.1.7 on 2023-06-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiuserapp', '0005_cartdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Image',
        ),
    ]
