# Generated by Django 4.1.7 on 2023-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiuserapp', '0006_remove_cartdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('User_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address1', models.CharField(blank=True, max_length=100, null=True)),
                ('Address2', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Zip', models.IntegerField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_on_card', models.CharField(blank=True, max_length=100, null=True)),
                ('credi_card_number', models.IntegerField(blank=True, null=True)),
                ('Expire_date', models.IntegerField(blank=True, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
