# Generated by Django 4.1.7 on 2023-06-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiuserapp', '0008_alter_checkoutdb_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdb',
            old_name='credi_card_number',
            new_name='credit_card_number',
        ),
    ]
